package:
  name: "msys"
  version: "1.7.359"

source:
  path: ../.
  use_gitignore: true # note: defaults to true

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - scons
    - numpy >=1.24,<2
    - pybind11
    - python
    - libboost
    - libboost-devel
    - rdkit

  host:
    - python
    - numpy >=1.24,<2
    - pybind11
    - libboost
    - libboost-devel
    - rapidjson
    - zlib
    - rdkit

  run:
    - python
    - libboost
    - libboost-devel
    - rdkit
    - ${{ pin_compatible('numpy') }}
    - ${{ pin_compatible('libboost') }}

tests:
  - python: 
      imports:
        - msys
  - script:
      - dms-diff -h
      - dms-dump -h
      - dms-find-knot -h
      - dms-fix-mass -h
      - dms-fix-water-residues -h
      - dms-frame -h
      - dms-grease -h
      - dms-info -h
      - dms-posre -h
      - dms-reorder-atoms -h
      - dms-replicate -h
      - dms-select -h
      - dms-sequence -h
      - dms-set -h
      - dms-solvate -h
      - dms-thermalize -h
      - dms-tile -h
      - dms-validate -h
      - dms-version -h
      - dms2mae -h
      # Ensure that lpsolve is linked properly
      - python -c 'import msys; s = msys.FromSmilesString("CC"); msys.AssignBondOrderAndFormalCharge(s)'

about:
  homepage: https://github.com/DEShawResearch/msys
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Tools for preparation and analysis of systems for molecular dynamics
  description: |
    Msys is a library for inspecting and manipulating chemical structures of
    the sort used in molecular simulations. Its main features include:
    Efficient representation of chemical systems and forcefields;
       A powerful atom selection language;
       Command line tools for scripting common tasks;
       C++ and Python interfaces.
    Msys currently supports Python 2.7 and Python 3.6+.
